### PR TITLE
Possible conversion to TypeScript

### PR DESCRIPTION
**Pull request by rossng**
I have a few ideas for features that I'd like to implement in the future, and in the process I converted the addon to TypeScript and reorganised it a bit. 

I thought I should offer this back to the main repository, but no worries if you don't want to merge it - it is quite an extreme change!

### CODE REVIEW

**Comment by kindohm** [comment]
@rossng thanks for the work! I'm about to take a look. Can you briefly describe the future ideas you have that these changes would support? I do appreciate the code re-organization and tweaks to get the project to a more maintainable and "modern" state. I will review.

**Comment by rossng** [comment]
Sure, here are some of the things I was thinking about:

* recording playback history so that it can be edited and replayed
* type hints or some kind of integration with the haskell-ide-engine/LSP VS Code addon
* redefining the 'BootTidal' file to distinguish between GHCi commands and actual Haskell code
* full Stack support, allowing you to import Haskell modules directly from your Stack project
* more robust starting/restarting of Supercollider and Tidal
* possible automatic initialisation of the SuperCollider server

etc.

**Comment by kindohm** [comment]
@rossng ah, yes, all good things. 

What is your motivation to change to TypeScript? Is it primarily the type-checking and OOP-style of programming to enable test mocking? Personal preference?

I suppose a change to TypeScript could be good since it is the de facto language used by VS Code and most extensions. I personally prefer the non-OOP style that plain JavaScript drives, but I'm not really using that style in the extension anyway. It's probably better to be consistent with most of the VS Code extensions out there. 

I've also been considering moving this repository to be under the TidalCycles organization instead of my personal GitHub account. With that, it might be beneficial to use a more community-accepted language (TypeScript) if it is moved.

**Comment by rossng** [comment]
Yes - essentially all those things. I'm a big fan of typed languages and I think it will make it will make the extension easier to maintain, particularly if multiple people contribute to it. It will also make it easier to do some unit testing (though this is a little tricky with it talking to GHCi so much).

Using the OOP stuff makes it easy to encapsulate things like `ensureTidalBooted` into a class rather than explicitly calling the functions each time you want to do something.

**Comment by kindohm** [comment]
@rossng I'd like to get this extension moved to the TidalCycles org on GitHub, then we can complete this PR. I realize that this will require you to fork the repo again but I think this is the right thing to do. I will try and get this done as soon as I can, possibly within hours, otherwise tonight.

**Comment by kindohm** [comment]
@rossng code has been forked at TidalCycles: https://github.com/tidalcycles/vscode-tidalcycles

I apologize for forking/moving the repo while you have changes in progress, but if you could submit a new PR on that repo then I think we can move forward with your changes.

**Comment by rossng** [comment]
👍 

I am going to try and add a few useful tests to make sure I haven't broken anything, then I will submit the PR on the new repository.

**Pull request merged**
